[package]
name = "rivet-toolchain-ffi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde_json = "1.0"
tokio = { version = "1.27", default-features = false, features = ["rt"] }
toolchain = { path = "../rivet-toolchain/", package = "rivet-toolchain" }

