[package]
name = "rivet-backend-embed"
version = "0.1.0"
build = "build.rs"
license = "Apache-2.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
include_dir = "0.7.4"
tokio = { version = "1.40.0", default-features = false, features = ["fs", "rt-multi-thread"] }

[build-dependencies]
anyhow = "1.0"
merkle_hash = "3.7.0"
rivet-deno-embed = { path = "../deno-embed", features = ["ignore-override-target"] }
sha2 = "0.10.8"
tempfile = "3.13.0"
tokio = { version = "1.40.0", default-features = false, features = ["fs", "rt-multi-thread"] }
walkdir = "2.5.0"
